version: "3"
services:
  service_broker:
    build: ./frontend
    ports:
      - "5011:5011"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - FLASK_DEBUG=0
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
    command: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:5011 wsgi:app --no-sendfile
    depends_on:
      - redis
      - mosquitto

  service_worker:
    build: ./backend
    ports:
      - "5012:5012"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 worker.py
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: any

  aggregator:
    build: ./aggregator
    ports:
      - "5013:5013"
    command: python3 worker.py
    volumes:
      - ./aggregator:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: any

  redis:
    container_name: redis
    image: redis
    ports:
      - "6380:6380"
    expose:
      - "6380"
    command: redis-server --port 6380
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data
      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log

  services:
    # Define an InfluxDB service
    influxdb:
      image: influxdb:1.7.3-alpine
      volumes:
        - ./data/influxdb:/var/lib/influxdb
      ports:
        - "8086:8086"
